version: '3'

services:
    db:
        image: mysql
        container_name: db_container
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_container
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        networks:
            - dev
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile.php
        container_name: php_container
        restart: always
        volumes:
            - ./:/var/www/
        networks:
            - dev

    nginx:
        image: nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/var/www/
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: