version: '3'

services:
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/
        networks:
            - dev
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: my_database

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        restart: always
        ports:
            - "8000:80"
        networks:
            - dev
        environment:
            VIRTUAL_HOST: ludo.23prod.dev
            VIRTUAL_PORT: 8000
            LETSENCRYPT_HOST: ludo.23prod.dev
            LETSENCRYPT_EMAIL: jahanlud@gmail.com

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: my_database
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dev

networks:
    dev:

volumes:
    mysql_data:

