version: '3'

services:
    php:
        build:
            context: .
            dockerfile: /php/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/
        networks:
            - dev
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: my_database

    nginx:
        build:
            context: .
            dockerfile: /nginx/Dockerfile
        restart: always
        ports:
            - "8000:80"
        networks:
            - dev

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: my_database
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dev

networks:
    dev:

volumes:
    mysql_data:

#volumes:
#    db-data:

    #    db:
    #        image: mysql
    #        container_name: db_container
    #        restart: always
    #        volumes:
    #            - db-data:/var/lib/mysql
    #        environment:
    #            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #        networks:
    #            - dev
    #
    #    phpmyadmin:
    #        image: phpmyadmin
    #        container_name: phpmyadmin_container
    #        restart: always
    #        depends_on:
    #            - db
    #        ports:
    #            - "8080:80"
    #        environment:
    #            PMA_HOST: db
    #        networks:
    #            - dev

