version: '3'

services:
    php:
        build:
            context: .
            dockerfile: /php/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/
        networks:
            - dev

    nginx:
        build:
            context: .
            dockerfile: /nginx/Dockerfile
        restart: always
        ports:
            - "8000:80"
        networks:
            - dev

networks:
    dev:

#volumes:
#    db-data:

    #    db:
    #        image: mysql
    #        container_name: db_container
    #        restart: always
    #        volumes:
    #            - db-data:/var/lib/mysql
    #        environment:
    #            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #        networks:
    #            - dev
    #
    #    phpmyadmin:
    #        image: phpmyadmin
    #        container_name: phpmyadmin_container
    #        restart: always
    #        depends_on:
    #            - db
    #        ports:
    #            - "8080:80"
    #        environment:
    #            PMA_HOST: db
    #        networks:
    #            - dev